### ISSUE TITLE
Training and Testing Datasets Download 

### ISSUE THREAD

**Issue by SaadShakeel414** [zyainfal/Joint-Holistic-and-Masked-Face-Recognition#1]
Hi! Thank you for sharing the code. Can you please provide the Baidu Link for downloading the training and testing datasets? After multiple attempts, I failed to download the datasets from the provided Google drive link due to network failure issue. Baidu will be more convenient, as i am working in China. Thank you.

**Comment by zyainfal** [comment]
Hi, I have uploaded the data to Baidu Pan:
Link：https://pan.baidu.com/s/1zBFL85oXf5afKeJQmiMumw 
Code：vbjc
